export const chatActionTypes = {
    LOGGING_IN_START: 'LOGGING_IN_START',

    UPDATE_CURRENT_SEARCH_LINE: 'UPDATE_CURRENT_SEARCH_LINE',
    CREATE_CHAT_START: 'CREATE_CHAT_START',
    SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT',

    // Updating input texts
    UPDATE_CURRENT_CHAT_MESSAGE: 'UPDATE_CURRENT_CHAT_MESSAGE',
    UPDATE_CURRENT_ID_INSTANCE: 'UPDATE_CURRENT_ID_INSTANCE',
    UPDATE_CURRENT_API_TOKEN: 'UPDATE_CURRENT_API_TOKEN',

    // Sending messages action types
    SEND_MESSAGE_START: 'SEND_MESSAGE_START',
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE',

    // Receiving messages action types
    RECEIVE_MESSAGE_START: 'RECEIVE_MESSAGE_START',
    RECEIVE_MESSAGE_SUCCESS: 'RECEIVE_MESSAGE_SUCCESS',
    RECEIVE_MESSAGE_FAILURE: 'RECEIVE_MESSAGE_FAILURE',

    // Deleting notification action types
    DELETING_NOTIFICATION_START: 'DELETING_NOTIFICATION_START',
    DELETING_NOTIFICATION_SUCCESS: 'DELETING_NOTIFICATION_SUCCESS',
    DELETING_NOTIFICATION_FAILURE: 'DELETING_NOTIFICATION_FAILURE'
}
